apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: admin
    openshift.io/sa.scc.mcs: s0:c13,c7
    openshift.io/sa.scc.supplemental-groups: 1000170000/10000
    openshift.io/sa.scc.uid-range: 1000170000/10000
  creationTimestamp: null
  name: business-app
spec:
  finalizers:
  - kubernetes

