apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: business-app
  namespace: argocd
spec:
  project: business-app
  source:
    repoURL: https://github.com/bisbeb/argocd-apps.git
    targetRevision: HEAD
    path: business-app
  destination:
    server: https://kubernetes.default.svc
    namespace: business-app
  ignoreDifferences:
  - group: apps
    kind: Route
    jsonPointers:
    - /status/ingress/conditions
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: business-app
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'

